### ISSUE TITLE
About your projects, especially geometry-toolkit

### ISSUE THREAD

**Issue by hwpplayer1** [ajmwagar/geometry-toolkit#1]
Hi Avery Wagar, 

This is Mert Gör, from Turkey, I'm interested in your projects especially this geometry-toolkit. 

How can i contribute ? Do you still want to commit ?

Thanks, happy hacking!

**Comment by ajmwagar** [comment]
Oh wow. Just saw this. I'd happily take prs.

I took geometry about two years ago, this repository is a collection of Scripts to help aid me in those classes.

If you have contributions I'd happily add them to the repository.￼￼

**Comment by hwpplayer1** [comment]
> Oh wow. Just saw this. I'd happily take prs.
> 
> I took geometry about two years ago, this repository is a collection of Scripts to help aid me in those classes.
> 
> If you have contributions I'd happily add them to the repository.￼￼

Thanks for your reply. I will make something and I want to do that.

**Comment by ajmwagar** [comment]
Looking forward to whatever you contribute.

Closing for now.
